package ifneeded lcd 1.0 [list source [file join $dir lcd.tcl]]
package ifneeded gps 1.0 [list source [file join $dir gps.tcl]]
package ifneeded led 1.0 [list source [file join $dir led.tcl]]
package ifneeded tmr 1.0 [list source [file join $dir tmr.tcl]]
package ifneeded loc 1.0 [list source [file join $dir loc.tcl]]
